version: "3"
services:
  microservice1:
    build: ./microservice1
    ports:
      - "5001:5001"
  microservice2:
    build: ./microservice2
    ports:
      - "5002:5002"
  microservice4:
    build: ./microservice4
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - microservice1
      - microservice2
      - microservice4


